/*
 * The MIT License
 *
 * Copyright 2015 amr.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

/**
 *
 * @author amr
 */
import controller.DB;
import controller.QuizController;
import controller.Session;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Random;
import javax.swing.JPanel;
import model.Question;
import model.Quiz;
import model.ShortAnswerQuestion;
import model.TrueFalseQuestion;
import model.UserType;
import model.MultipleChoiceQuestion;

public class MainJframe extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public MainJframe() {
        questionCounter = 0;
        qc = new QuizController();

        quizList = DB.readFromDB();

        int quiz_count = quizList.size();

        /*
         generate
        
         */
        Random random = new Random();
        quiz_id = random.nextInt(quiz_count);

        if (quizList == null) {
            System.out.println("Error in retrieving quiz list.");
        }

        for (int i = 0; i < quiz_count; i++) {
            quizList.set(i, DB.loadQuiz(i + 1));
        }

        Quiz qu = quizList.get(quiz_id);

        int size = qu.getQuestions().size();
        answered = new boolean[size];
        Arrays.fill(answered, false);

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        login = new javax.swing.JPanel();
        LoginBtn = new javax.swing.JButton();
        RegisterBtn = new javax.swing.JButton();
        l_username = new javax.swing.JTextField();
        l_username_l = new javax.swing.JLabel();
        l_password_l = new javax.swing.JLabel();
        l_password = new javax.swing.JPasswordField();
        register = new javax.swing.JPanel();
        r_backbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        r_username = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        r_submitBtn = new javax.swing.JButton();
        r_password = new javax.swing.JPasswordField();
        r_passwordconf = new javax.swing.JPasswordField();
        err_l = new javax.swing.JLabel();
        teacher = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        quizTable = new javax.swing.JTable();
        addQBtn = new javax.swing.JButton();
        editQBtn = new javax.swing.JButton();
        tryQBtn = new javax.swing.JButton();
        student = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ansText = new javax.swing.JTextArea();
        trueStdRadioBtn = new javax.swing.JRadioButton();
        falseStdRadioBtn = new javax.swing.JRadioButton();
        backStdBtn = new javax.swing.JButton();
        submitStdBtn = new javax.swing.JButton();
        nextStdBtn = new javax.swing.JButton();
        finishStdBtn = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        quesText = new javax.swing.JTextArea();
        stdChoiceBtn1 = new javax.swing.JRadioButton();
        stdChoiceBtn2 = new javax.swing.JRadioButton();
        stdChoiceBtn3 = new javax.swing.JRadioButton();
        addQuesPanel = new javax.swing.JPanel();
        qType = new javax.swing.JPanel();
        FiBBtn = new javax.swing.JButton();
        TFBtn = new javax.swing.JButton();
        ShABtn = new javax.swing.JButton();
        MCQBtn = new javax.swing.JButton();
        addQPanel = new javax.swing.JPanel();
        fillBlankPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        fbQuesText = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        fbAnsText = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        FiBSubmit = new javax.swing.JButton();
        finish3 = new javax.swing.JButton();
        TorFPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tfQuesText = new javax.swing.JTextArea();
        TorFSubmit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        trueRadioBtn1 = new javax.swing.JRadioButton();
        falseRadioBtn1 = new javax.swing.JRadioButton();
        finish2 = new javax.swing.JButton();
        MCQPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        MCQuesText = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        choiceBtn1 = new javax.swing.JRadioButton();
        choiceBtn2 = new javax.swing.JRadioButton();
        choiceBtn3 = new javax.swing.JRadioButton();
        choiceText1 = new javax.swing.JTextField();
        choiceText2 = new javax.swing.JTextField();
        choiceText3 = new javax.swing.JTextField();
        MCQSubmit = new javax.swing.JButton();
        finish1 = new javax.swing.JButton();
        finishQuizPanel = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        finishText = new javax.swing.JTextArea();

        buttonGroup1.add(trueRadioBtn1);
        buttonGroup1.add(falseRadioBtn1);

        buttonGroup2.add(choiceBtn1);
        buttonGroup2.add(choiceBtn2);
        buttonGroup2.add(choiceBtn3);

        buttonGroup3.add(trueStdRadioBtn);
        buttonGroup3.add(falseStdRadioBtn);

        buttonGroup4.add(stdChoiceBtn1);
        buttonGroup4.add(stdChoiceBtn2);
        buttonGroup4.add(stdChoiceBtn3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.CardLayout());

        LoginBtn.setText("Login");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });

        RegisterBtn.setText("Register");
        RegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBtnActionPerformed(evt);
            }
        });

        l_username.setText("student1");
        l_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_usernameActionPerformed(evt);
            }
        });

        l_username_l.setText("Username");

        l_password_l.setText("Password");

        l_password.setText("123456");

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(l_username)
                        .addGroup(loginLayout.createSequentialGroup()
                            .addComponent(LoginBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RegisterBtn))
                        .addGroup(loginLayout.createSequentialGroup()
                            .addGap(78, 78, 78)
                            .addComponent(l_password_l))
                        .addComponent(l_password, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(l_username_l)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(l_username_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(l_password_l)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginBtn)
                    .addComponent(RegisterBtn))
                .addGap(52, 52, 52))
        );

        mainPanel.add(login, "card3");

        r_backbtn.setText("< Back");
        r_backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_backbtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Username");
        jLabel3.setToolTipText("");

        r_username.setText("student1");

        jLabel4.setText("Password");
        jLabel4.setToolTipText("");

        jLabel5.setText("Confirm Password");
        jLabel5.setToolTipText("");

        r_submitBtn.setText("Submit");
        r_submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_submitBtnActionPerformed(evt);
            }
        });

        r_password.setText("123456");

        r_passwordconf.setText("123456");
        r_passwordconf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_passwordconfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerLayout = new javax.swing.GroupLayout(register);
        register.setLayout(registerLayout);
        registerLayout.setHorizontalGroup(
            registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(r_backbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(err_l)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(r_submitBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerLayout.createSequentialGroup()
                .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(r_passwordconf)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registerLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(206, Short.MAX_VALUE))
            .addGroup(registerLayout.createSequentialGroup()
                .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerLayout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jLabel4))
                    .addGroup(registerLayout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel3))
                    .addGroup(registerLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(r_username, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(r_password, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        registerLayout.setVerticalGroup(
            registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(r_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(r_passwordconf, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r_backbtn)
                            .addComponent(r_submitBtn))
                        .addContainerGap())
                    .addGroup(registerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(err_l)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        mainPanel.add(register, "card2");

        quizTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "# of Qs", "Instructor"
            }
        )
        {public boolean isCellEditable(int row, int column) {return false;}}
    );
    quizTable.setName(""); // NOI18N
    jScrollPane1.setViewportView(quizTable);

    addQBtn.setText("Add Quiz");
    addQBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            addQBtnActionPerformed(evt);
        }
    });

    editQBtn.setText("Edit Quiz");

    tryQBtn.setText("Try Quiz");

    javax.swing.GroupLayout teacherLayout = new javax.swing.GroupLayout(teacher);
    teacher.setLayout(teacherLayout);
    teacherLayout.setHorizontalGroup(
        teacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(teacherLayout.createSequentialGroup()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
            .addGroup(teacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(editQBtn)
                .addGroup(teacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addQBtn)
                    .addComponent(tryQBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(27, 27, 27))
    );
    teacherLayout.setVerticalGroup(
        teacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        .addGroup(teacherLayout.createSequentialGroup()
            .addGap(36, 36, 36)
            .addComponent(addQBtn)
            .addGap(50, 50, 50)
            .addComponent(editQBtn)
            .addGap(43, 43, 43)
            .addComponent(tryQBtn)
            .addContainerGap(127, Short.MAX_VALUE))
    );

    mainPanel.add(teacher, "card2");

    ansText.setColumns(20);
    ansText.setRows(5);
    jScrollPane6.setViewportView(ansText);

    trueStdRadioBtn.setText("true");

    falseStdRadioBtn.setText("false");

    backStdBtn.setText("< Back");
    backStdBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            backStdBtnActionPerformed(evt);
        }
    });

    submitStdBtn.setText("Submit");
    submitStdBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            submitStdBtnActionPerformed(evt);
        }
    });

    nextStdBtn.setText("Next >");
    nextStdBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            nextStdBtnActionPerformed(evt);
        }
    });

    finishStdBtn.setText("Finish");
    finishStdBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            finishStdBtnActionPerformed(evt);
        }
    });

    quesText.setColumns(20);
    quesText.setRows(5);
    quesText.setEnabled(false);
    jScrollPane7.setViewportView(quesText);

    stdChoiceBtn1.setText("a");

    stdChoiceBtn2.setText("b");

    stdChoiceBtn3.setText("c");

    javax.swing.GroupLayout studentLayout = new javax.swing.GroupLayout(student);
    student.setLayout(studentLayout);
    studentLayout.setHorizontalGroup(
        studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(studentLayout.createSequentialGroup()
            .addGroup(studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(studentLayout.createSequentialGroup()
                    .addGroup(studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(studentLayout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(backStdBtn)
                            .addGap(70, 70, 70)
                            .addGroup(studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(trueStdRadioBtn)
                                .addComponent(submitStdBtn)))
                        .addGroup(studentLayout.createSequentialGroup()
                            .addGap(148, 148, 148)
                            .addComponent(stdChoiceBtn1)
                            .addGap(61, 61, 61)
                            .addComponent(stdChoiceBtn2)))
                    .addGap(8, 8, 8)
                    .addGroup(studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentLayout.createSequentialGroup()
                            .addComponent(finishStdBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                            .addComponent(nextStdBtn)
                            .addGap(29, 29, 29))
                        .addGroup(studentLayout.createSequentialGroup()
                            .addGroup(studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(falseStdRadioBtn)
                                .addGroup(studentLayout.createSequentialGroup()
                                    .addGap(52, 52, 52)
                                    .addComponent(stdChoiceBtn3)))
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addGroup(studentLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane6)
                        .addComponent(jScrollPane7))))
            .addContainerGap())
    );
    studentLayout.setVerticalGroup(
        studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(studentLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(trueStdRadioBtn)
                .addComponent(falseStdRadioBtn))
            .addGap(18, 18, 18)
            .addGroup(studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(stdChoiceBtn1)
                .addComponent(stdChoiceBtn2)
                .addComponent(stdChoiceBtn3))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
            .addGroup(studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(backStdBtn)
                .addComponent(submitStdBtn)
                .addComponent(nextStdBtn)
                .addComponent(finishStdBtn))
            .addContainerGap())
    );

    mainPanel.add(student, "card3");

    FiBBtn.setText("Fill in Blank");
    FiBBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            FiBBtnActionPerformed(evt);
        }
    });

    TFBtn.setText("True or False");
    TFBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            TFBtnActionPerformed(evt);
        }
    });

    ShABtn.setText("Short Answer");
    ShABtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            ShABtnActionPerformed(evt);
        }
    });

    MCQBtn.setText("Multiple Choice");
    MCQBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            MCQBtnActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout qTypeLayout = new javax.swing.GroupLayout(qType);
    qType.setLayout(qTypeLayout);
    qTypeLayout.setHorizontalGroup(
        qTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(qTypeLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(FiBBtn)
            .addGap(18, 18, 18)
            .addComponent(TFBtn)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ShABtn)
            .addGap(18, 18, 18)
            .addComponent(MCQBtn)
            .addGap(22, 22, 22))
    );
    qTypeLayout.setVerticalGroup(
        qTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, qTypeLayout.createSequentialGroup()
            .addContainerGap(21, Short.MAX_VALUE)
            .addGroup(qTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(FiBBtn)
                .addComponent(TFBtn)
                .addComponent(ShABtn)
                .addComponent(MCQBtn))
            .addContainerGap())
    );

    addQPanel.setLayout(new java.awt.CardLayout());

    fbQuesText.setColumns(20);
    fbQuesText.setRows(5);
    jScrollPane2.setViewportView(fbQuesText);

    fbAnsText.setColumns(20);
    fbAnsText.setRows(5);
    jScrollPane3.setViewportView(fbAnsText);

    jLabel8.setText("Qusetion:   ");

    jLabel9.setText("Answer:  ");

    FiBSubmit.setText("Submit");
    FiBSubmit.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            FiBSubmitActionPerformed(evt);
        }
    });

    finish3.setText("Finish");
    finish3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            finish3ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout fillBlankPanelLayout = new javax.swing.GroupLayout(fillBlankPanel);
    fillBlankPanel.setLayout(fillBlankPanelLayout);
    fillBlankPanelLayout.setHorizontalGroup(
        fillBlankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(fillBlankPanelLayout.createSequentialGroup()
            .addGroup(fillBlankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fillBlankPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(fillBlankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                    .addGroup(fillBlankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                        .addComponent(jScrollPane3)))
                .addGroup(fillBlankPanelLayout.createSequentialGroup()
                    .addGap(218, 218, 218)
                    .addComponent(FiBSubmit)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(finish3)))
            .addContainerGap())
    );
    fillBlankPanelLayout.setVerticalGroup(
        fillBlankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(fillBlankPanelLayout.createSequentialGroup()
            .addGroup(fillBlankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fillBlankPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(fillBlankPanelLayout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(jLabel8)))
            .addGroup(fillBlankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fillBlankPanelLayout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(fillBlankPanelLayout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jLabel9)))
            .addGap(18, 18, 18)
            .addGroup(fillBlankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(FiBSubmit)
                .addComponent(finish3))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    addQPanel.add(fillBlankPanel, "card2");

    jLabel2.setText("Question:");

    tfQuesText.setColumns(20);
    tfQuesText.setRows(5);
    jScrollPane4.setViewportView(tfQuesText);

    TorFSubmit.setText("Submit");
    TorFSubmit.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            TorFSubmitActionPerformed(evt);
        }
    });

    jLabel1.setText("Answer:");

    trueRadioBtn1.setText("True");
    trueRadioBtn1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            trueRadioBtn1ActionPerformed(evt);
        }
    });

    falseRadioBtn1.setText("False");

    finish2.setText("Finish");
    finish2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            finish2ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout TorFPanelLayout = new javax.swing.GroupLayout(TorFPanel);
    TorFPanel.setLayout(TorFPanelLayout);
    TorFPanelLayout.setHorizontalGroup(
        TorFPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TorFPanelLayout.createSequentialGroup()
            .addGap(31, 31, 31)
            .addGroup(TorFPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jLabel2)
                .addComponent(jLabel1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
            .addGroup(TorFPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TorFPanelLayout.createSequentialGroup()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TorFPanelLayout.createSequentialGroup()
                    .addComponent(trueRadioBtn1)
                    .addGap(93, 93, 93)
                    .addComponent(falseRadioBtn1)
                    .addGap(106, 106, 106))))
        .addGroup(TorFPanelLayout.createSequentialGroup()
            .addGap(221, 221, 221)
            .addComponent(TorFSubmit)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(finish2)
            .addContainerGap())
    );
    TorFPanelLayout.setVerticalGroup(
        TorFPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(TorFPanelLayout.createSequentialGroup()
            .addGroup(TorFPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TorFPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(TorFPanelLayout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(jLabel2)))
            .addGap(23, 23, 23)
            .addGroup(TorFPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(trueRadioBtn1)
                .addComponent(falseRadioBtn1))
            .addGap(53, 53, 53)
            .addGroup(TorFPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(TorFSubmit)
                .addComponent(finish2))
            .addContainerGap(59, Short.MAX_VALUE))
    );

    addQPanel.add(TorFPanel, "card3");

    jLabel7.setText("Question");

    MCQuesText.setColumns(20);
    MCQuesText.setRows(5);
    jScrollPane5.setViewportView(MCQuesText);

    jLabel11.setText("Answer");

    choiceBtn1.setText("a");
    choiceBtn1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            choiceBtn1ActionPerformed(evt);
        }
    });

    choiceBtn2.setText("b");

    choiceBtn3.setText("c");

    choiceText1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            choiceText1ActionPerformed(evt);
        }
    });

    MCQSubmit.setText("Submit");
    MCQSubmit.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            MCQSubmitActionPerformed(evt);
        }
    });

    finish1.setText("Finish");
    finish1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            finish1ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout MCQPanelLayout = new javax.swing.GroupLayout(MCQPanel);
    MCQPanel.setLayout(MCQPanelLayout);
    MCQPanelLayout.setHorizontalGroup(
        MCQPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(MCQPanelLayout.createSequentialGroup()
            .addGroup(MCQPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MCQPanelLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addGroup(MCQPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(jLabel11))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                    .addGroup(MCQPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(MCQPanelLayout.createSequentialGroup()
                            .addGroup(MCQPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(choiceBtn1)
                                .addComponent(choiceBtn2)
                                .addComponent(choiceBtn3))
                            .addGap(35, 35, 35)
                            .addGroup(MCQPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(choiceText1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                .addComponent(choiceText2)))))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MCQPanelLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(MCQPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(choiceText3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MCQSubmit))
                    .addGap(136, 136, 136)
                    .addComponent(finish1)))
            .addContainerGap())
    );
    MCQPanelLayout.setVerticalGroup(
        MCQPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(MCQPanelLayout.createSequentialGroup()
            .addGroup(MCQPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MCQPanelLayout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(jLabel7)))
            .addGroup(MCQPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MCQPanelLayout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(jLabel11))
                .addGroup(MCQPanelLayout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addGroup(MCQPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(choiceBtn1)
                        .addComponent(choiceText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(MCQPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(choiceBtn2)
                        .addComponent(choiceText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(MCQPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(choiceBtn3)
                .addComponent(choiceText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
            .addGroup(MCQPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(MCQSubmit)
                .addComponent(finish1))
            .addContainerGap())
    );

    addQPanel.add(MCQPanel, "card5");

    javax.swing.GroupLayout addQuesPanelLayout = new javax.swing.GroupLayout(addQuesPanel);
    addQuesPanel.setLayout(addQuesPanelLayout);
    addQuesPanelLayout.setHorizontalGroup(
        addQuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(qType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(addQPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    addQuesPanelLayout.setVerticalGroup(
        addQuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(addQuesPanelLayout.createSequentialGroup()
            .addComponent(qType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(addQPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    mainPanel.add(addQuesPanel, "card6");

    finishQuizPanel.setPreferredSize(new java.awt.Dimension(520, 342));

    finishText.setColumns(20);
    finishText.setRows(5);
    finishText.setEnabled(false);
    jScrollPane8.setViewportView(finishText);

    javax.swing.GroupLayout finishQuizPanelLayout = new javax.swing.GroupLayout(finishQuizPanel);
    finishQuizPanel.setLayout(finishQuizPanelLayout);
    finishQuizPanelLayout.setHorizontalGroup(
        finishQuizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, finishQuizPanelLayout.createSequentialGroup()
            .addContainerGap(119, Short.MAX_VALUE)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(116, 116, 116))
    );
    finishQuizPanelLayout.setVerticalGroup(
        finishQuizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(finishQuizPanelLayout.createSequentialGroup()
            .addGap(89, 89, 89)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(113, Short.MAX_VALUE))
    );

    mainPanel.add(finishQuizPanel, "card7");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // TODO add your handling code here:
        Session.login(l_username.getText(), l_password.getPassword());
        if (Session.getCurrent().getType() == UserType.Instructor) {
            Switch(teacher);
        } else {
            Question q = quizList.get(quiz_id).getQuestions().get(questionCounter);
            String question = "Question 1\n";
            question += q.getQuestion();
            setEditability(q, answered[0]);
            quesText.setText(question);
            Switch(student);
        }
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void RegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBtnActionPerformed
        // TODO add your handling code here:
        Switch(register);
    }//GEN-LAST:event_RegisterBtnActionPerformed

    private void l_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l_usernameActionPerformed

    private void r_backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_backbtnActionPerformed
        // TODO add your handling code here:
        Switch(login);
    }//GEN-LAST:event_r_backbtnActionPerformed

    private void r_submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_submitBtnActionPerformed
        // TODO add your handling code here:
        error = "";

        if (!Arrays.equals(r_password.getPassword(), r_passwordconf.getPassword())) {
            printError("Password doesnt match.");
            return;
        }

        if (r_password.getPassword().length < 6) {
            printError("Password must be at least 6 characters.");
            return;
        }

        if (r_username.getText().length() < 4) {
            printError("Username must be at least 4 characters.");
            return;
        }

        if (error == null) {
            l_username.setText(r_username.getText());
            Switch(login);
        }

        printError(Session.register(r_username.getText(), r_password.getPassword()));
    }//GEN-LAST:event_r_submitBtnActionPerformed

    private void r_passwordconfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_passwordconfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_passwordconfActionPerformed

    private void addQBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQBtnActionPerformed
        // TODO add your handling code here:
        Switch(addQuesPanel);
        QuizController.incrementQuizCount();
    }//GEN-LAST:event_addQBtnActionPerformed

    private void ShABtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShABtnActionPerformed
        // TODO add your handling code here:
        SwitchQ(fillBlankPanel);
    }//GEN-LAST:event_ShABtnActionPerformed

    private void FiBBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiBBtnActionPerformed
        // TODO add your handling code here:
        SwitchQ(fillBlankPanel);
    }//GEN-LAST:event_FiBBtnActionPerformed

    private void TFBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFBtnActionPerformed
        // TODO add your handling code here:
        SwitchQ(TorFPanel);
    }//GEN-LAST:event_TFBtnActionPerformed

    private void MCQBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCQBtnActionPerformed
        // TODO add your handling code here:
        SwitchQ(MCQPanel);
    }//GEN-LAST:event_MCQBtnActionPerformed

    private void FiBSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiBSubmitActionPerformed
        // TODO add your shandling code here:
        String[] s = new String[2];
        s[0] = fbQuesText.getText();
        s[1] = fbAnsText.getText();
        qc.addShortQuestion(s);
    }//GEN-LAST:event_FiBSubmitActionPerformed

    private void trueRadioBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trueRadioBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trueRadioBtn1ActionPerformed

    private void MCQSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCQSubmitActionPerformed
        // TODO add your handling code here:
        String[] s = new String[4];
        s[0] = MCQuesText.getText();
        s[1] = choiceText1.getText();
        s[2] = choiceText2.getText();
        s[3] = choiceText3.getText();
        int trueChoice = choiceBtn1.isSelected() ? 1 : choiceBtn2.isSelected() ? 2 : 3;
        boolean[] b = new boolean[3];
        for (int i = 0; i < 3; i++) {
            b[i] = false;
        }
        b[trueChoice - 1] = true;
        qc.addMCQuestion(s, b);
    }//GEN-LAST:event_MCQSubmitActionPerformed

    private void choiceBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choiceBtn1ActionPerformed

    private void choiceText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choiceText1ActionPerformed

    private void TorFSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TorFSubmitActionPerformed
        // TODO add your handling code here:
        String question = tfQuesText.getText();
        boolean answer = trueRadioBtn1.isSelected();
        qc.addTFQuestion(question, answer);
    }//GEN-LAST:event_TorFSubmitActionPerformed

    private void finish1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finish1ActionPerformed
        // TODO add your handling code here:
        DB.writeToDB(qc);
        Switch(teacher);
    }//GEN-LAST:event_finish1ActionPerformed

    private void finish3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finish3ActionPerformed
        // TODO add your handling code here:
        DB.writeToDB(qc);
        Switch(teacher);
    }//GEN-LAST:event_finish3ActionPerformed

    private void finish2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finish2ActionPerformed
        // TODO add your handling code here:
        DB.writeToDB(qc);
        Switch(teacher);
    }//GEN-LAST:event_finish2ActionPerformed

    private void nextStdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextStdBtnActionPerformed
        // TODO add your handling code here:
        quesText.setText("");
        questionCounter++;
        if (questionCounter >= (quizList.get(quiz_id).getQuestions().size())) {
            questionCounter = 0;
        }
        int id = questionCounter;
        Question q = quizList.get(quiz_id).getQuestions().get(questionCounter);
        String question = "Question " + (id + 1) + "\n";
        question += q.getQuestion();
        setEditability(q, answered[id]);
        quesText.setText(question);
    }//GEN-LAST:event_nextStdBtnActionPerformed

    private void backStdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backStdBtnActionPerformed
        // TODO add your handling code here:
        quesText.setText("");
        questionCounter--;
        if (questionCounter < 0) {
            questionCounter = (quizList.get(quiz_id).getQuestions().size() - 1);
        }
        int id = questionCounter;
        Question q = quizList.get(quiz_id).getQuestions().get(questionCounter);
        String question = "Question " + (id + 1) + "\n";
        question += q.getQuestion();
        setEditability(q, answered[id]);
        quesText.setText(question);
    }//GEN-LAST:event_backStdBtnActionPerformed

    private void submitStdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitStdBtnActionPerformed
        // TODO add your handling code here:
        int id = questionCounter;
        answered[id] = true;
        Quiz qu = quizList.get(quiz_id);
        Question q = qu.getQuestions().get(id);
        if (q instanceof TrueFalseQuestion) {
            boolean answer = trueStdRadioBtn.isSelected();
            boolean correct = q.checkAnswer(answer);
            if (correct) {
                qu.incrementScore();
            }
        } else if (q instanceof ShortAnswerQuestion) {
            String answer = ansText.getText();
            boolean correct = q.checkAnswer(answer);
            if (correct) {
                qu.incrementScore();
            }
        } else {
            MultipleChoiceQuestion q1 = (MultipleChoiceQuestion) qu.getQuestions().get(id);

            int answerIndex = stdChoiceBtn1.isSelected() ? 1 : stdChoiceBtn2.isSelected() ? 2 : 3;
            String answer;
            switch (answerIndex) {
                case 1:
                    answer = q1.getChoice(0);
                    break;
                case 2:
                    answer = q1.getChoice(1);
                    break;
                default:
                    answer = q1.getChoice(2);
            }
            boolean correct = q.checkAnswer(answer);
            if (correct) {
                qu.incrementScore();
            }
        }
        setEditability(null, answered[id]);

    }//GEN-LAST:event_submitStdBtnActionPerformed

    private void finishStdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishStdBtnActionPerformed
        // TODO add your handling code here:
        int score = quizList.get(quiz_id).getScore();
        int numQues = quizList.get(quiz_id).getQuestions().size();
        String finish = "Congratulations !\nYou finished the quiz.\n";
        finish += "Your score was " + score + "/" + numQues + ".";
        finishText.setText(finish);
        Switch(finishQuizPanel);
    }//GEN-LAST:event_finishStdBtnActionPerformed

    public void printError(String er) {
        error = er;
        err_l.setText(error);
    }

    public void SwitchQ(JPanel jp) {
        addQPanel.removeAll();
        addQPanel.add(jp);
        addQPanel.repaint();
        addQPanel.revalidate();
    }

    public void Switch(JPanel jp) {
        mainPanel.removeAll();
        mainPanel.add(jp);
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    public void setEditability(Question q, boolean answered) {

        if (answered) {
            ansText.setEditable(false);
            trueStdRadioBtn.setEnabled(false);
            falseStdRadioBtn.setEnabled(false);
            stdChoiceBtn1.setEnabled(false);
            stdChoiceBtn2.setEnabled(false);
            stdChoiceBtn3.setEnabled(false);
            return;
        }

        if (q == null) {
            return;
        }

        if (q instanceof TrueFalseQuestion) {
            ansText.setEditable(false);
            trueStdRadioBtn.setEnabled(true);
            falseStdRadioBtn.setEnabled(true);
            stdChoiceBtn1.setEnabled(false);
            stdChoiceBtn2.setEnabled(false);
            stdChoiceBtn3.setEnabled(false);
        } else if (q instanceof ShortAnswerQuestion) {
            ansText.setEditable(true);
            trueStdRadioBtn.setEnabled(false);
            falseStdRadioBtn.setEnabled(false);
            stdChoiceBtn1.setEnabled(false);
            stdChoiceBtn2.setEnabled(false);
            stdChoiceBtn3.setEnabled(false);
        } else {
            ansText.setEditable(false);
            trueStdRadioBtn.setEnabled(false);
            falseStdRadioBtn.setEnabled(false);
            stdChoiceBtn1.setEnabled(true);
            stdChoiceBtn2.setEnabled(true);
            stdChoiceBtn3.setEnabled(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainJframe().setVisible(true);
            }
        });
    }

    private String error = "";
    private int questionCounter;
    private QuizController qc;
    private ArrayList<Quiz> quizList;
    private boolean[] answered;
    private int quiz_id;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FiBBtn;
    private javax.swing.JButton FiBSubmit;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JButton MCQBtn;
    private javax.swing.JPanel MCQPanel;
    private javax.swing.JButton MCQSubmit;
    private javax.swing.JTextArea MCQuesText;
    private javax.swing.JButton RegisterBtn;
    private javax.swing.JButton ShABtn;
    private javax.swing.JButton TFBtn;
    private javax.swing.JPanel TorFPanel;
    private javax.swing.JButton TorFSubmit;
    private javax.swing.JButton addQBtn;
    private javax.swing.JPanel addQPanel;
    private javax.swing.JPanel addQuesPanel;
    private javax.swing.JTextArea ansText;
    private javax.swing.JButton backStdBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JRadioButton choiceBtn1;
    private javax.swing.JRadioButton choiceBtn2;
    private javax.swing.JRadioButton choiceBtn3;
    private javax.swing.JTextField choiceText1;
    private javax.swing.JTextField choiceText2;
    private javax.swing.JTextField choiceText3;
    private javax.swing.JButton editQBtn;
    private javax.swing.JLabel err_l;
    private javax.swing.JRadioButton falseRadioBtn1;
    private javax.swing.JRadioButton falseStdRadioBtn;
    private javax.swing.JTextArea fbAnsText;
    private javax.swing.JTextArea fbQuesText;
    private javax.swing.JPanel fillBlankPanel;
    private javax.swing.JButton finish1;
    private javax.swing.JButton finish2;
    private javax.swing.JButton finish3;
    private javax.swing.JPanel finishQuizPanel;
    private javax.swing.JButton finishStdBtn;
    private javax.swing.JTextArea finishText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JPasswordField l_password;
    private javax.swing.JLabel l_password_l;
    private javax.swing.JTextField l_username;
    private javax.swing.JLabel l_username_l;
    private javax.swing.JPanel login;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton nextStdBtn;
    private javax.swing.JPanel qType;
    private javax.swing.JTextArea quesText;
    private javax.swing.JTable quizTable;
    private javax.swing.JButton r_backbtn;
    private javax.swing.JPasswordField r_password;
    private javax.swing.JPasswordField r_passwordconf;
    private javax.swing.JButton r_submitBtn;
    private javax.swing.JTextField r_username;
    private javax.swing.JPanel register;
    private javax.swing.JRadioButton stdChoiceBtn1;
    private javax.swing.JRadioButton stdChoiceBtn2;
    private javax.swing.JRadioButton stdChoiceBtn3;
    private javax.swing.JPanel student;
    private javax.swing.JButton submitStdBtn;
    private javax.swing.JPanel teacher;
    private javax.swing.JTextArea tfQuesText;
    private javax.swing.JRadioButton trueRadioBtn1;
    private javax.swing.JRadioButton trueStdRadioBtn;
    private javax.swing.JButton tryQBtn;
    // End of variables declaration//GEN-END:variables
}
